"use client";

import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronDown, Headphones, Lightbulb, Play, Sparkles } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { useActionFeedback } from "@/components/action-feedback";
import { Badge, ProgressBar, cn } from "@/components/ui";

export function LessonDetailView({ kind, slug }: { kind: "grammar" | "course"; slug: string }) {
  const isGrammar = kind === "grammar";
  const title = isGrammar ? slug.replaceAll("-", " ").replace(/\b\w/g, (character) => character.toUpperCase()) : slug === "english-b1" ? "English B1 · Build momentum" : "Academic English · Make your ideas clear";
  const [completed, setCompleted] = useState(false);
  const [outlineIndex, setOutlineIndex] = useState(0);
  const { notify } = useActionFeedback();
  const toggleComplete = () => { setCompleted((value) => !value); notify(completed ? "Lesson reopened so you can practice again." : "Lesson marked complete."); };
  return <div className="lesson-page page-enter"><div className="lesson-top"><Link href={isGrammar ? "/app/grammar" : "/app/courses"} className="back-link"><ArrowLeft size={15} /> Back to {isGrammar ? "grammar" : "courses"}</Link><span>{isGrammar ? "Grammar studio" : "Course path"}</span><span>Lesson 01</span></div><div className="lesson-layout"><main><div className="lesson-heading"><div><p className="eyebrow eyebrow-blue">{isGrammar ? "Grammar lesson · B1" : "Unit 01 · Guided lesson"}</p><h1>{title}</h1><p>{isGrammar ? "See the structure, notice it in context, then use it in a sentence that belongs to you." : "A connected lesson across vocabulary, grammar, listening, and reflection."}</p></div><Badge tone={isGrammar ? "blue" : "purple"}>{isGrammar ? "B1" : "36 lessons"}</Badge></div><div className="lesson-progress"><span>Lesson progress</span><strong>{completed ? "100%" : "18%"}</strong><ProgressBar value={completed ? 100 : 18} tone={isGrammar ? "primary" : "purple"} /></div>{isGrammar ? <GrammarLesson /> : <CourseLesson />}</main><aside className="lesson-outline"><p className="eyebrow">{isGrammar ? "In this lesson" : "Course outline"}</p><h3>{isGrammar ? "Present perfect" : "English B1"}</h3>{["Notice the idea", "See the structure", "Practice in context", "Quick check"].map((item, index) => <button type="button" className={cn("outline-item", index === outlineIndex && "outline-item-active")} onClick={() => { setOutlineIndex(index); notify(`${item} selected.`, "info"); }} key={item}><span>{index + 1}</span><strong>{item}</strong><ChevronDown size={14} /></button>)}<div className="outline-note"><Lightbulb size={15} /><span>Keep your answer short and specific. Clarity is the goal.</span></div></aside></div><div className="lesson-actions"><Link href={isGrammar ? "/app/grammar" : "/app/courses"} className="button button-secondary"><ArrowLeft size={15} /> Previous</Link><button type="button" className="button button-primary" onClick={toggleComplete}>{completed ? "Reopen lesson" : "Mark complete"} {completed ? <Check size={15} /> : <ArrowRight size={15} />}</button></div></div>;
}

function GrammarLesson() {
  const [answer, setAnswer] = useState("");
  const { notify } = useActionFeedback();
  const choose = (value: string) => { setAnswer(value); notify(value === "I have studied English for three years." ? "Correct — the duration connects the past to now." : "Look for the sentence using have or has plus a past participle.", value === "I have studied English for three years." ? "success" : "info"); };
  return <div className="lesson-body"><article className="lesson-explanation"><span className="lesson-step">01 · Notice</span><h2>Connect the past to now.</h2><p>Use the present perfect when a past action matters now, or when you are talking about experience without saying exactly when it happened.</p><div className="grammar-structure"><span>Subject</span><strong>+</strong><span>have / has</span><strong>+</strong><span>past participle</span><em>She has studied English for three years.</em></div></article><article className="lesson-example"><div className="example-heading"><BookOpen size={17} /><span>In context</span></div><p>“Researchers <strong>have developed</strong> a faster way to measure reading fluency.”</p><small>The result is relevant now.</small></article><div className="lesson-practice"><div className="lesson-step">03 · Practice</div><h2>Choose the sentence that connects past and present.</h2><div className="practice-options">{["I studied English yesterday.", "I have studied English for three years.", "I am studying English tomorrow."].map((option) => <button type="button" className={answer === option ? "practice-selected" : ""} key={option} onClick={() => choose(option)}>{option}</button>)}</div></div></div>;
}

function CourseLesson() {
  const { notify } = useActionFeedback();
  const playIntroduction = () => { if ("speechSynthesis" in window) window.speechSynthesis.speak(new SpeechSynthesisUtterance("A useful word has a life. Start with a word, meet it in a sentence, listen for its rhythm, then return to it later.")); notify("Introduction playing.", "info"); };
  return <div className="lesson-body"><article className="lesson-explanation course-lesson-banner"><span className="lesson-step">Unit 01 · Everyday systems</span><h2>A useful word has a life.</h2><p>Start with a word, meet it in a sentence, listen for its rhythm, then return to it later. This is how a collection becomes a skill.</p><div className="course-lesson-actions"><button type="button" className="button button-dark" onClick={playIntroduction}><Play size={14} fill="currentColor" /> Play introduction</button><span><Headphones size={14} /> 2:30</span></div></article><div className="lesson-blocks"><button type="button" onClick={() => notify("Vocabulary practice is ready in the dictionary.", "info")}><span className="block-icon block-blue"><BookOpen size={16} /></span><strong>Vocabulary</strong><small>10 words · development, evidence…</small></button><button type="button" onClick={() => notify("Grammar practice is ready in the lesson.", "info")}><span className="block-icon block-purple"><Sparkles size={16} /></span><strong>Grammar</strong><small>Present perfect in context</small></button><button type="button" onClick={() => notify("Quick check opened. Aim for 80% to pass.", "info")}><span className="block-icon block-green"><Check size={16} /></span><strong>Quick check</strong><small>5 questions · 80% to pass</small></button></div></div>;
}
